name: prasasti
description: Indonesian Face Recognition for Crime Cases
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  image_picker: ^1.1.0
  flutter_riverpod: ^2.5.0
  shared_preferences: ^2.2.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
